on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches: main

name: Reply to Twitter Mentions

jobs:
  render:
    name: Reply to Twitter Mentions
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install dependencies
        run: Rscript -e 'install.packages(c("rtweet","dplyr","lubridate","jsonlite"))'
      - name: Run the bot
        env: 
          TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: Rscript bot.R
      - name: Commit results
        run: |
          git add -A
          git commit -m 'Replied to more tweets' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
